services:
  - type: web
    name: customer-backend-staging
    runtime: image
    image:
      url: ghcr.io/daze17/furever_home/customer-backend-staging
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: staging
